name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-dev python3-pip \
          libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
          libsmpeg-dev libportmidi-dev libavformat-dev libswscale-dev \
          gcc

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install Pygame
      run: pip install pygame==2.0.1

    - name: Run unit tests
      run: python -m unittest discover -s tests -p 'test_*.py'
